spring:
   application:
      name: dev.simulator
   thymeleaf:
      cache: false
      mode: HTML
      prefix: classpath:/templates/
      suffix: .html
   main:
      allow-bean-definition-overriding: true
      banner-mode: off
   web:
      resources:
         add-mappings: true

# DBについての設定
   datasource:
      hikari:
         connectionTimeout: '20000'
         minimumIdle: '10'
         schema: scm_xxx
         maximumPoolSize: '50'
      password: xxxx
      username: xxx
      url: jdbc:postgresql://192.170.xx.xx:5532/devdb

# サーバについての設定
server:
   servlet:
      context-path: /simulator
      session:
         timeout: 30m
   error:
      whitelabel:
         enabled: false
   port: '8080'

# mybatisについての設定
mybatis:
   mapper-locations: classpath*:mapper/*.xml
   type-aliases-package: jp.co.necsoft.rrmg.entity
   configuration:
      map-underscore-to-camel-case: true
      default-statement-timeout: 30