package com.hyron.example.dev.simulator.entity;

import java.io.Serializable;
import java.util.Date;

/**
 * Database Table Remarks:
 *   ユーザー情報
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table scm_liuwu.user_info
 */
public class UserInfo implements Serializable {

  /**
   * Database Column Remarks: ユーザーID This field was generated by MyBatis Generator. This field corresponds to the database column scm_liuwu.user_info.user_id
   * @mbg.generated
   */
  private String userId;
  /**
   * Database Column Remarks: ユーザー名 This field was generated by MyBatis Generator. This field corresponds to the database column scm_liuwu.user_info.user_name
   * @mbg.generated
   */
  private String userName;
  /**
   * Database Column Remarks: パスワード This field was generated by MyBatis Generator. This field corresponds to the database column scm_liuwu.user_info.password
   * @mbg.generated
   */
  private String password;
  /**
   * Database Column Remarks: 更新日時 This field was generated by MyBatis Generator. This field corresponds to the database column scm_liuwu.user_info.insert_date
   * @mbg.generated
   */
  private Date insertDate;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database table scm_liuwu.user_info
   * @mbg.generated
   */
  private static final long serialVersionUID = 1L;

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column scm_liuwu.user_info.user_id
   * @return  the value of scm_liuwu.user_info.user_id
   * @mbg.generated
   */
  public String getUserId() {
    return userId;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column scm_liuwu.user_info.user_id
   * @param userId  the value for scm_liuwu.user_info.user_id
   * @mbg.generated
   */
  public void setUserId(String userId) {
    this.userId = userId;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column scm_liuwu.user_info.user_name
   * @return  the value of scm_liuwu.user_info.user_name
   * @mbg.generated
   */
  public String getUserName() {
    return userName;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column scm_liuwu.user_info.user_name
   * @param userName  the value for scm_liuwu.user_info.user_name
   * @mbg.generated
   */
  public void setUserName(String userName) {
    this.userName = userName;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column scm_liuwu.user_info.password
   * @return  the value of scm_liuwu.user_info.password
   * @mbg.generated
   */
  public String getPassword() {
    return password;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column scm_liuwu.user_info.password
   * @param password  the value for scm_liuwu.user_info.password
   * @mbg.generated
   */
  public void setPassword(String password) {
    this.password = password;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column scm_liuwu.user_info.insert_date
   * @return  the value of scm_liuwu.user_info.insert_date
   * @mbg.generated
   */
  public Date getInsertDate() {
    return insertDate;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column scm_liuwu.user_info.insert_date
   * @param insertDate  the value for scm_liuwu.user_info.insert_date
   * @mbg.generated
   */
  public void setInsertDate(Date insertDate) {
    this.insertDate = insertDate;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table scm_liuwu.user_info
   * @mbg.generated
   */
  @Override
  public boolean equals(Object that) {
    if (this == that) {
      return true;
    }
    if (that == null) {
      return false;
    }
    if (getClass() != that.getClass()) {
      return false;
    }
    UserInfo other = (UserInfo) that;
    return (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
        && (this.getUserName() == null ? other.getUserName() == null : this.getUserName().equals(other.getUserName()))
        && (this.getPassword() == null ? other.getPassword() == null : this.getPassword().equals(other.getPassword()))
        && (this.getInsertDate() == null ? other.getInsertDate() == null
            : this.getInsertDate().equals(other.getInsertDate()));
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table scm_liuwu.user_info
   * @mbg.generated
   */
  @Override
  public int hashCode() {
    final int prime = 31;
    int result = 1;
    result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
    result = prime * result + ((getUserName() == null) ? 0 : getUserName().hashCode());
    result = prime * result + ((getPassword() == null) ? 0 : getPassword().hashCode());
    result = prime * result + ((getInsertDate() == null) ? 0 : getInsertDate().hashCode());
    return result;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table scm_liuwu.user_info
   * @mbg.generated
   */
  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append(getClass().getSimpleName());
    sb.append(" [");
    sb.append("Hash = ").append(hashCode());
    sb.append(", userId=").append(userId);
    sb.append(", userName=").append(userName);
    sb.append(", password=").append(password);
    sb.append(", insertDate=").append(insertDate);
    sb.append(", serialVersionUID=").append(serialVersionUID);
    sb.append("]");
    return sb.toString();
  }
}