package com.hyron.example.dev.simulator.mapper;

import com.hyron.example.dev.simulator.entity.UserInfo;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface UserInfoMapper {

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table scm_liuwu.user_info
   * @mbg.generated
   */
  int deleteByPrimaryKey(String userId);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table scm_liuwu.user_info
   * @mbg.generated
   */
  int insert(UserInfo row);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table scm_liuwu.user_info
   * @mbg.generated
   */
  UserInfo selectByPrimaryKey(String userId);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table scm_liuwu.user_info
   * @mbg.generated
   */
  List<UserInfo> selectAll();

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table scm_liuwu.user_info
   * @mbg.generated
   */
  int updateByPrimaryKey(UserInfo row);
}